### PR TITLE
Manage recipes

### PR DESCRIPTION
**Pull request by mhmxs**
@martonsereg @matyix plz review / accept / or just talk about it :)

### CODE REVIEW

**Comment by martonsereg** [comment]
Please change the timeout label to "Timeout (mins)" or something similar to be able to see that the value is in minutes.

**Comment by martonsereg** [comment]
Also I don't really like the "Stored plugin" checkbox, I think it would be better to have 2 large textfields like in the blueprints panel, where the user can paste their scripts instead of uploading it. And it should be default behavior as well, because I guess it will be the common use-case, not the plugin url.

**Comment by martonsereg** [comment]
And one last thing: the properties field is rarely used, so it should be under the script/url fields. But these are only my opinions so please discuss it with @matyix

**Comment by matyix** [comment]
Agree with @martonsereg. Other than that looks good.

**Comment by doktoric** [comment]
crypto.js not needed 'cause there is angular-base64

**Pull request merged**
